//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManahauMotelTake2.DataStuff
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Billing()
        {
            this.Joins = new HashSet<Join>();
        }
    
        public int BillingID { get; set; }
        public Nullable<decimal> BarCharge { get; set; }
        public Nullable<decimal> WiFiCharge { get; set; }
        public Nullable<decimal> TelephoneCharge { get; set; }
        public decimal RoomCharge { get; set; }
        public Nullable<int> BookingIDFK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Join> Joins { get; set; }
    }
}
