//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManahauMotelTake2.DataStuff
{
    using System;
    using System.Collections.Generic;
    
    public partial class Join
    {
        public int JoinID { get; set; }
        public int RoomIDFK { get; set; }
        public int BookingIDFK { get; set; }
        public Nullable<int> BillingIDFK { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Room Room { get; set; }
        public virtual Billing Billing { get; set; }
    }
}
